"""check_schedule (T06)

Revision ID: 03665cf5a894
Revises: e2b4151202a4
Create Date: 2026-07-20 18:22:16.830988
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03665cf5a894'
down_revision: str | None = 'e2b4151202a4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_schedule',
    sa.Column('domain_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('rdap', 'whois', 'ssl', 'vt', 'healthcheck', name='check_type', native_enum=False, length=16), nullable=False),
    sa.Column('next_check_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('domain_id', 'type')
    )
    op.create_index('ix_check_schedule_type_next', 'check_schedule', ['type', 'next_check_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_check_schedule_type_next', table_name='check_schedule')
    op.drop_table('check_schedule')
    # ### end Alembic commands ###
