"""ssl_certificates (T08)

Revision ID: 100985e73616
Revises: 22ca9ba9bd20
Create Date: 2026-07-20 18:43:15.919619
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '100985e73616'
down_revision: str | None = '22ca9ba9bd20'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ssl_certificates',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('domain_id', sa.BigInteger(), nullable=False),
    sa.Column('host', sa.String(length=253), nullable=False),
    sa.Column('issuer', sa.String(length=512), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('san', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ssl_certificates_domain_id'), 'ssl_certificates', ['domain_id'], unique=False)
    op.create_index(op.f('ix_ssl_certificates_valid_to'), 'ssl_certificates', ['valid_to'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ssl_certificates_valid_to'), table_name='ssl_certificates')
    op.drop_index(op.f('ix_ssl_certificates_domain_id'), table_name='ssl_certificates')
    op.drop_table('ssl_certificates')
    # ### end Alembic commands ###
