"""registrar default project

Revision ID: 124616430a20
Revises: de5459c76458
Create Date: 2026-07-21 17:03:30.739494
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '124616430a20'
down_revision: str | None = 'de5459c76458'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'registrar_accounts', sa.Column('default_project_id', sa.BigInteger(), nullable=True)
    )
    op.create_foreign_key(
        'fk_registrar_accounts_default_project_id',
        'registrar_accounts',
        'projects',
        ['default_project_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_registrar_accounts_default_project_id', 'registrar_accounts', type_='foreignkey'
    )
    op.drop_column('registrar_accounts', 'default_project_id')
    # ### end Alembic commands ###
