"""alert rules and events (T12)

Revision ID: 1d02dbde3f59
Revises: 9a9e33ca6f3d
Create Date: 2026-07-20 19:29:40.619942
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d02dbde3f59'
down_revision: str | None = '9a9e33ca6f3d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('rule_id', sa.BigInteger(), nullable=True),
    sa.Column('domain_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('dedupe_key', sa.String(length=128), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('state', sa.String(length=8), nullable=False),
    sa.Column('fired_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_events_domain_id'), 'alert_events', ['domain_id'], unique=False)
    op.create_index('ix_alert_events_domain_state', 'alert_events', ['domain_id', 'state'], unique=False)
    op.create_index('uq_alert_event_active', 'alert_events', ['dedupe_key'], unique=True, postgresql_where=sa.text("state = 'active'"))
    op.create_table('alert_rules',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('scope_id', sa.BigInteger(), nullable=True),
    sa.Column('condition_type', sa.String(length=32), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_rules')
    op.drop_index('uq_alert_event_active', table_name='alert_events', postgresql_where=sa.text("state = 'active'"))
    op.drop_index('ix_alert_events_domain_state', table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_domain_id'), table_name='alert_events')
    op.drop_table('alert_events')
    # ### end Alembic commands ###
