"""registrars, accounts, unassigned + domain FKs (T16)

Revision ID: 81d9ed1584b9
Revises: cbce6deeeef0
Create Date: 2026-07-20 20:14:43.716624
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81d9ed1584b9'
down_revision: str | None = 'cbce6deeeef0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registrars',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('connector_type', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('registrar_accounts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('registrar_id', sa.BigInteger(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('credentials_enc', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['registrar_id'], ['registrars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registrar_accounts_registrar_id'), 'registrar_accounts', ['registrar_id'], unique=False)
    op.create_table('unassigned_domains',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('registrar_account_id', sa.BigInteger(), nullable=False),
    sa.Column('fqdn', sa.String(length=253), nullable=False),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['registrar_account_id'], ['registrar_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unassigned_domains_fqdn'), 'unassigned_domains', ['fqdn'], unique=True)
    op.create_index(op.f('ix_unassigned_domains_registrar_account_id'), 'unassigned_domains', ['registrar_account_id'], unique=False)
    op.create_foreign_key(
        'fk_domains_registrar_id', 'domains', 'registrars',
        ['registrar_id'], ['id'], ondelete='SET NULL',
    )
    op.create_foreign_key(
        'fk_domains_registrar_account_id', 'domains', 'registrar_accounts',
        ['registrar_account_id'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_domains_registrar_account_id', 'domains', type_='foreignkey')
    op.drop_constraint('fk_domains_registrar_id', 'domains', type_='foreignkey')
    op.drop_index(op.f('ix_unassigned_domains_registrar_account_id'), table_name='unassigned_domains')
    op.drop_index(op.f('ix_unassigned_domains_fqdn'), table_name='unassigned_domains')
    op.drop_table('unassigned_domains')
    op.drop_index(op.f('ix_registrar_accounts_registrar_id'), table_name='registrar_accounts')
    op.drop_table('registrar_accounts')
    op.drop_table('registrars')
    # ### end Alembic commands ###
