"""notification channels and log (T11)

Revision ID: 9a9e33ca6f3d
Revises: 39c3caccc2e0
Create Date: 2026-07-20 19:18:40.781115
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a9e33ca6f3d'
down_revision: str | None = '39c3caccc2e0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_channels',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('config_enc', sa.Text(), nullable=True),
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('digest_time', sa.String(length=5), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_channels_company_id'), 'notification_channels', ['company_id'], unique=False)
    op.create_index(op.f('ix_notification_channels_is_default'), 'notification_channels', ['is_default'], unique=False)
    op.create_index(op.f('ix_notification_channels_is_enabled'), 'notification_channels', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_notification_channels_project_id'), 'notification_channels', ['project_id'], unique=False)
    op.create_table('notification_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('alert_event_id', sa.BigInteger(), nullable=True),
    sa.Column('digest_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('delivery_status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['notification_channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_log_alert_event_id'), 'notification_log', ['alert_event_id'], unique=False)
    op.create_index(op.f('ix_notification_log_channel_id'), 'notification_log', ['channel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_log_channel_id'), table_name='notification_log')
    op.drop_index(op.f('ix_notification_log_alert_event_id'), table_name='notification_log')
    op.drop_table('notification_log')
    op.drop_index(op.f('ix_notification_channels_project_id'), table_name='notification_channels')
    op.drop_index(op.f('ix_notification_channels_is_enabled'), table_name='notification_channels')
    op.drop_index(op.f('ix_notification_channels_is_default'), table_name='notification_channels')
    op.drop_index(op.f('ix_notification_channels_company_id'), table_name='notification_channels')
    op.drop_table('notification_channels')
    # ### end Alembic commands ###
