"""user mcp_allowed flag

Revision ID: c309a4097dc4
Revises: 124616430a20
Create Date: 2026-07-21 18:08:04.953077
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c309a4097dc4'
down_revision: str | None = '124616430a20'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('mcp_allowed', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # Drop the server default now that existing rows are backfilled to false; the
    # model default (Python-side) governs new rows.
    op.alter_column('users', 'mcp_allowed', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mcp_allowed')
    # ### end Alembic commands ###
