"""user totp 2fa fields (T22)

Revision ID: de5459c76458
Revises: e8545037123e
Create Date: 2026-07-20 21:50:11.701166
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de5459c76458'
down_revision: str | None = 'e8545037123e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('totp_secret_enc', sa.String(length=255), nullable=True))
    # server_default so the column can be added NOT NULL to a table with existing rows.
    op.add_column(
        'users',
        sa.Column('totp_enabled', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('users', 'totp_enabled', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'totp_enabled')
    op.drop_column('users', 'totp_secret_enc')
    # ### end Alembic commands ###
