"""domains, domain_tags, field history (T04)

Revision ID: e2b4151202a4
Revises: 1f2a0416a1c9
Create Date: 2026-07-20 17:58:13.221241
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2b4151202a4'
down_revision: str | None = '1f2a0416a1c9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('fqdn', sa.String(length=253), nullable=False),
    sa.Column('punycode', sa.String(length=253), nullable=False),
    sa.Column('tld', sa.String(length=63), nullable=False),
    sa.Column('registrar_id', sa.BigInteger(), nullable=True),
    sa.Column('registrar_account_id', sa.BigInteger(), nullable=True),
    sa.Column('registration_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=True),
    sa.Column('epp_statuses', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('nameservers', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('registrant', sa.String(length=255), nullable=True),
    sa.Column('renewal_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('renewal_currency', sa.String(length=3), nullable=False),
    sa.Column('renewal_period_months', sa.Integer(), nullable=False),
    sa.Column('ssl_extra_hosts', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('field_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('responsible_user_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domains_expiry_date'), 'domains', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_domains_fqdn'), 'domains', ['fqdn'], unique=True)
    op.create_index(op.f('ix_domains_is_active'), 'domains', ['is_active'], unique=False)
    op.create_index(op.f('ix_domains_project_id'), 'domains', ['project_id'], unique=False)
    op.create_index(op.f('ix_domains_punycode'), 'domains', ['punycode'], unique=False)
    op.create_index(op.f('ix_domains_registrar_id'), 'domains', ['registrar_id'], unique=False)
    op.create_index(op.f('ix_domains_tld'), 'domains', ['tld'], unique=False)
    op.create_table('domain_field_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('domain_id', sa.BigInteger(), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('old', sa.Text(), nullable=True),
    sa.Column('new', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_field_history_changed_at'), 'domain_field_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_domain_field_history_domain_id'), 'domain_field_history', ['domain_id'], unique=False)
    op.create_table('domain_tags',
    sa.Column('domain_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('domain_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('domain_tags')
    op.drop_index(op.f('ix_domain_field_history_domain_id'), table_name='domain_field_history')
    op.drop_index(op.f('ix_domain_field_history_changed_at'), table_name='domain_field_history')
    op.drop_table('domain_field_history')
    op.drop_index(op.f('ix_domains_tld'), table_name='domains')
    op.drop_index(op.f('ix_domains_registrar_id'), table_name='domains')
    op.drop_index(op.f('ix_domains_punycode'), table_name='domains')
    op.drop_index(op.f('ix_domains_project_id'), table_name='domains')
    op.drop_index(op.f('ix_domains_is_active'), table_name='domains')
    op.drop_index(op.f('ix_domains_fqdn'), table_name='domains')
    op.drop_index(op.f('ix_domains_expiry_date'), table_name='domains')
    op.drop_table('domains')
    # ### end Alembic commands ###
